### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by PSBM2002** [MetalWorkerTools/CNCL#1]
CNCL connects to my Arduino and then crashes and automatically closes. 

When I open the app, select my COM port and click "Connect", it flashes "Initializing"-"Checking Build"-"Reading Config" and then closes. Not sure why

**Comment by HuubBuis** [comment]
What grbl version are you running?

You need 1.1f or compatible

**Comment by HuubBuis** [comment]
No complaints any more, so probably solved, closing.
