### ISSUE TITLE
App stuck in !Unsupported Licence State!

### ISSUE THREAD

**Issue by NeilMarley** [MetalWorkerTools/CNCL#2]
**Describe the bug**
Have downloaded to trial - on 2 separate devices. Each time get valid 30-day trial  expiry date shown but App will not run beyond help & licence pages..

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 

**Additional context**

**Comment by HuubBuis** [comment]
I am not sure about the error, Could you please post a screenshot to clarify?

**Comment by NeilMarley** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/81095808/111910279-a383a180-8a58-11eb-8dec-ca7750407480.png)

**Comment by HuubBuis** [comment]
This is strange, this error should not (can not) appear but is does. 

The account you use on your PC should be the account used for downloading the app.

Please uninstall the app, reinstall the app and than run it using the account you used for installing it.

Let me know if it worked.

**Comment by HuubBuis** [comment]
I have checked the Microsoft information portal. I can't find any trial license usage since the last release. Sadly You are the first that reported an issue. I will setup a clean PC environment for debugging.

**Comment by NeilMarley** [comment]
Hi Huub,

 

I tried uninstall & a clean re-install on both devices, when logged-in as the Microsoft account holder and the Demo version still didn’t work. Same error as before, shows a valid 30-day trial date  but !Invalid Licence… etc and all of the licence/purchase options greyed-out.

 

I opted to pay for an App Licence + 1 Year (2 separate transactions…?) which now works.

 

It looks like the issue is with the Trial setup…. 

 

Neil

**Comment by HuubBuis** [comment]
Neil,
The PC is being installed, this will take some time because it hasn't run for a long time.
I can only debug a trial license for 30 days on a fresh installed PC.  For that the trial license is tested every release by simulating what is not completely the same.

Thank you for buying a license. I will report a soon as I have a trial license running.

Huub

**Comment by NeilMarley** [comment]
Hi Huub,

 

No problem, I have enough with the 12 month licence to have a play.

 

Neil

**Comment by HuubBuis** [comment]
Neil,
I have found the error. It was a bug introduced by me.
I have released version 2.3.69 with some enhancements that also fixes this issue.

Take care and stay healthy

Huub

**Comment by HuubBuis** [comment]
I can’t get a new version released by Microsoft that has a trial option **and** usage license options. To avoid wasting any more time I have decided to drop the one year and permanent usage licenses. All current and new owners of an app license can use the app without limitations.
