### ISSUE TITLE
Engraving chars on an Arduino Uno will flood the buffers

### ISSUE THREAD

**Issue by MetalWorkerTools** [MetalWorkerTools/CNCL#4]
Release 2.3.71
Engraving chars on an Arduino Uno will flood the buffers. This will result in Grbl error messages and the chars are not engraved properly. This only happens on the Uno,  due to the low buffer size on this board.

As a workaround you can set the (High/Low) speed to Low, that will fix the problem for now.
It will be solved in the next release.

**Comment by HuubBuis** [comment]
This is fixed in release 2.3.75
